### ISSUE TITLE
Create Meta files

### ISSUE THREAD

**Issue by tum-aweink** [tum-aweink/ThesisPrototype#4]
Missing files for Swift Package:

- [x] package.swift (.platforms required)
- [x] Readme.md optional?
- [x] folder structure needs to be created
